name: Sync Main Project

on:
  schedule:
    - cron: '0 0 * * *' # Daily at midnight
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Automation Repo
        uses: actions/checkout@v2

      - name: Checkout Main Project Repo
        uses: actions/checkout@v2
        with:
          repository: jahorwitz/slopopedia
          path: main_project
